### ISSUE TITLE
UnicodeEncodeError with scopus_affiliation.py

### ISSUE THREAD

**Issue by Michael-E-Rose** [jkitchin/scopus#5]
There still seems to be a unicode issue in python 2.7 with certain authors.

This time it's with https://www.scopus.com/authid/detail.uri?authorId=6602884607

```
>>> from scopus.scopus_author import ScopusAuthor
>>> au = ScopusAuthor("6602884607", refresh=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/scopus/scopus_author.py", line 178, in __init__
    if el is not None]]
  File "/usr/local/lib/python2.7/dist-packages/scopus/scopus_affiliation.py", line 81, in __init__
    f.write(resp.text)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 1299: ordinal not in range(128)
```

**Comment by jkitchin** [comment]
Thanks for reporting that. I added a fix to scopus_affiliation.py that should fix that.

**Comment by Michael-E-Rose** [comment]
Yes, everything's working! Great :+1:
